/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule DeleteLinkMutation.graphql
 * @generated SignedSource<<9c6b9b6ff559595d6187c61777aff58a>>
 * @relayHash 7fc7e96d47f3167b2e56b1c950a6d08f
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';
export type deleteLinkInput = {
  id?: ?string;
};

export type DeleteLinkMutationResponse = {
  deletedId?: ?string;
};
*/


/*
mutation DeleteLinkMutation(
  $input: deleteLinkInput!
) {
  deleteLink(input: $input) {
    deletedId
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "deleteLinkInput!",
        "defaultValue": null
      }
    ],
    "kind": "Fragment",
    "metadata": null,
    "name": "DeleteLinkMutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "deleteLinkInput!"
          }
        ],
        "concreteType": "deleteLinkPayload",
        "name": "deleteLink",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "deletedId",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Mutation"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "DeleteLinkMutation",
  "query": {
    "argumentDefinitions": [
      {
        "kind": "LocalArgument",
        "name": "input",
        "type": "deleteLinkInput!",
        "defaultValue": null
      }
    ],
    "kind": "Root",
    "name": "DeleteLinkMutation",
    "operation": "mutation",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": [
          {
            "kind": "Variable",
            "name": "input",
            "variableName": "input",
            "type": "deleteLinkInput!"
          }
        ],
        "concreteType": "deleteLinkPayload",
        "name": "deleteLink",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "deletedId",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "mutation DeleteLinkMutation(\n  $input: deleteLinkInput!\n) {\n  deleteLink(input: $input) {\n    deletedId\n  }\n}\n"
};

module.exports = batch;
