/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule AddLinkViewerQuery.graphql
 * @generated SignedSource<<a51062f45482e4dfd46628d6c9e03775>>
 * @relayHash 83677f60a90cad376f6042aac6a0cb5d
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/


/*
query AddLinkViewerQuery {
  store {
    id
  }
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "AddLinkViewerQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Store",
        "name": "store",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "AddLinkViewerQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "AddLinkViewerQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "Store",
        "name": "store",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query AddLinkViewerQuery {\n  store {\n    id\n  }\n}\n"
};

module.exports = batch;
