/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Link_store.graphql
 * @generated SignedSource<<478ec888a34df6321a1b16f5e3adcc07>>
 * @flow
 * @nogrep
 */

/* eslint-disable */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Link_store = {|
  +id: string;
|};
*/


const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Link_store",
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "args": null,
      "name": "id",
      "storageKey": null
    }
  ],
  "type": "Store"
};

module.exports = fragment;
